<?xml version="1.0" encoding="utf-8"?><Database Name="NewsExercise" Class="DataClassesNewsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=NewsExercise;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NewsExerciseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Comment" Member="Comment">
    <Type Name="Comment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Autor" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="News_Comment" Member="News" ThisKey="NewsID" OtherKey="ID" Type="News" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="UserLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pwd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_News" Member="News" ThisKey="UserID" OtherKey="UserID" Type="News" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="News">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PubTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Abstract" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NewContext" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="News_Comment" Member="Comment" ThisKey="ID" OtherKey="NewsID" Type="Comment" />
      <Association Name="User_News" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="NewsType_News" Member="NewsType" ThisKey="TypeID" OtherKey="ID" Type="NewsType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewsType" Member="NewsType">
    <Type Name="NewsType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsType" Member="NewsType1" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="NewsType_News" Member="News" ThisKey="ID" OtherKey="TypeID" Type="News" />
    </Type>
  </Table>
</Database>